default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=2000']
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
        # The JSONs below support comments (against spec)
        exclude: ^(.eslintrc.json|tsconfig.json)
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
        exclude: ^conda-build/.*/meta.yaml
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: requirements-txt-fixer

    # Changes tabs to spaces
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
    -   id: remove-tabs
        exclude: "(^(.git|setup.cfg))|(.(json|scn)$)"

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.11.0
    hooks:
    -   id: pretty-format-ini
        args: [--autofix]
    -   id: pretty-format-toml
        args: [--autofix]
        additional_dependencies:
         - toml-sort==0.22.0

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the ref you want to point at
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore

-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/ambv/black
    rev: 23.10.0
    hooks:
    -   id: black
        args: ['--preview','--line-length=89']

-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place]

-   repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: ['--expand-star-imports', '--ignore-init-module-imports', '--in-place', '--remove-unused-variables', '--remove-all-unused-imports', '--remove-rhs-for-unused-variables']

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        exclude: docs/
        additional_dependencies: &flake8_dependencies
        - flake8-bugbear==23.1.20
        - flake8-builtins==1.5.3
        - flake8-comprehensions==3.10.0
        - flake8-return==1.2.0
        - flake8-simplify==0.17.0

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
    -   id: shellcheck
